version: 1.0.0.{build}

install:
  - ps: |
      &nuget.exe install PoshBuildTools -source https://ci.appveyor.com/nuget/PoshBuildTools -outputDirectory "$env:USERPROFILE\Documents\WindowsPowerShell\Modules\" -ExcludeVersion -Version 1.0.0.48
      Import-Module PoshBuildTools
      $moduleInfoList = @()
      $moduleInfoList += New-BuildModuleInfo -ModuleName 'ConvertToHtml' -ModulePath '.\ConvertToHtml' -CodeCoverage @('.\ConvertToHtml\exporttohtml.psm1') -Tests @('.\tests')
      Invoke-AppveyorInstall -InstallPester

build_script:
  - ps: |
      Import-Module .\PoshBuildTools
      Invoke-AppveyorBuild -moduleInfoList $moduleInfoList      

# Artifacts would not be collected if build failed. To do that, we use on_finish:
#-artifacts:
#  - path: nuget\*.nupkg

on_finish:
  - ps: |
      Import-Module .\PoshBuildTools
      Write-Info 'Creating Example zip ...'
      7z a -tzip .\out\examples.zip .\examples\*.html
      Invoke-AppveyorFinish -moduleInfoList $moduleInfoList -expectedModuleCount 1

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
test_script:
  - ps: |
      Import-Module .\ConvertToHtml -force
      Import-Module .\PoshBuildTools
      Invoke-AppveyorTest -moduleInfoList $moduleInfoList 
