version: 1.0.0.{build}

install:
  - cinst pester
  - ps: |
      $nuGetPath = "$env:SystemDrive\nuget.exe"
      $webClient = New-Object 'System.Net.WebClient';
      $webClient.DownloadFile( 'https://oneget.org/nuget-anycpu-2.8.3.6.exe', $nuGetPath )  

build_script:
  - ps: |
      $nuGetPath = "$env:SystemDrive\nuget.exe"
      mkdir -force .\out > $null
      mkdir -force .\nuget > $null
      mkdir -force .\examples > $null

      # Update version to current Build Version
      $versionParts = ($env:APPVEYOR_BUILD_VERSION).split('.')
      Import-Module .\ConvertToHtml
      $moduleInfo = Get-Module -Name ConvertToHtml
      $newVersion = New-Object -TypeName 'System.Version' -ArgumentList @($versionParts[0],$versionParts[1],$versionParts[2],$versionParts[3])
      $FunctionsToExport = @()
      foreach($key in $moduleInfo.ExportedFunctions.Keys)
      {
          $FunctionsToExport += $key
      }
      copy-item .\ConvertToHtml\ConvertTohtml.psd1 .\ConvertTohtmlOrigPsd1.ps1
      New-ModuleManifest -Path .\ConvertToHtml\ConvertTohtml.psd1 -Guid $moduleInfo.Guid -Author $moduleInfo.Author -CompanyName $moduleInfo.CompanyName `
       -Copyright $moduleInfo.Copyright -RootModule $moduleInfo.RootModule -ModuleVersion $newVersion -Description $moduleInfo.Description -FunctionsToExport $FunctionsToExport
      # Done Updating Version

      # Create Nuget package
      [xml]$xml = Get-Content -Raw .\ConvertToHtml\ConvertToHtml.nuspec
      $xml.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
      $xml.OuterXml | out-file -FilePath .\ConvertToHtml\ConvertToHtml.nuspec
      &$nuGetPath pack .\ConvertToHtml\ConvertToHtml.nuspec -outputdirectory  .\nuget

      7z a -tzip .\out\ConvertToHtml.zip .\ConvertToHtml\*.*
      

# Artifacts would not be collected if build failed. To do that, we use on_finish:
#-artifacts:
#  - path: nuget\*.nupkg

on_finish:
  - ps: |
      ls .\out | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - ps: |
      # setup variables for the whole build process
      #
      $script:failedTestsCount = 0
      $webClient = New-Object 'System.Net.WebClient';
      #
      function RunTest {
        param
        (
          [string]$filePath, [HashTable] $CodeCoverage
          )
          $testResultsFile = "TestsResults.xml"
          $res = Invoke-Pester -Path $filePath -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru -CodeCoverage $CodeCoverage
          $webClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
          return $res
      }
      #
      function Write-Info([string]$message) {
        Write-Host -ForegroundColor Yellow  "[APPVEYOR] [$([datetime]::UtcNow)] $message"
      }
      #
      Write-Info "Hello, I'm appveyor.yml! All messages from me, looks like this one."
      
      $coverage.CodeCoverage.MissedCommands | ConvertTo-FormattedHtml -OutClipboard
      $CodeCoverage = @('.\ConvertToHtml\exporttohtml.psm1')
      ".\tests" | %{ 
        $res = RunTest -filePath $_ -CodeCoverage @('.\ConvertToHtml\exporttohtml.psm1')
        $script:failedTestsCount += $res.FailedCount 
        $CodeCoverageTitle = "Code Coverage {0:F1}%"  -f (100 * ($res.CodeCoverage.NumberOfCommandsExecuted /$res.CodeCoverage.NumberOfCommandsAnalyzed))
        $res.CodeCoverage.MissedCommands | ConvertTo-FormattedHtml -title CodeCoverageTitle | out-file .\examples\CodeCoverage.html
      }

      7z a -tzip .\out\examples.zip .\examples\*.html
      
      if ($script:failedTestsCount -gt 0) { throw "$($script:failedTestsCount) tests failed."} else {       ls .\nuget | % { Push-AppveyorArtifact $_.FullName }}
